CUDA_VISIBLE_DEVICES=3 python train_ner.py \
    --batch-size 64 \
    --model-path ../shared_data/xlmr_6L \
    --format conll \
    --train-path data/mSystemEntity/train \
    --valid-path data/mSystemEntity/valid \
    --freeze_layer_count 0 \
    --epoch 5 \
    --do-eval \
    --do-train \
    --output-dir model/mSystemEntity
