CUDA_VISIBLE_DEVICES=0 python train_ner.py \
    --model-path ../../shared_data/bdi_roberta_4L_oscarwiki_envi/ \
    --format conll \
    --train-path data/mSystemEntity/train/vi.txt \
    --valid-path data/mSystemEntity/valid/vi.txt \
    --freeze_layer_count 0 \
    --epoch 10 \
    --do-eval \
    --do-train \
    --output-dir model/viSystemEntity \
    --use-crf